### ISSUE TITLE
android : 해시태그 검색하기

### ISSUE THREAD

**Issue by YeoeunJeong** [lay126/fuding_wewe#13]
# 에러메세지

08-23 01:47:51.616: E/AndroidRuntime(3422): Process: wewe.fuding.activity, PID: 3422
08-23 01:47:51.616: E/AndroidRuntime(3422): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
08-23 01:47:51.616: E/AndroidRuntime(3422):     at wewe.fuding.widget.Fragment_NewsFeed.init(Fragment_NewsFeed.java:214)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at wewe.fuding.widget.Fragment_NewsFeed.showNewsfeed(Fragment_NewsFeed.java:182)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at wewe.fuding.widget.Fragment_NewsFeed.access$1(Fragment_NewsFeed.java:86)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at wewe.fuding.widget.Fragment_NewsFeed$1.onClick(Fragment_NewsFeed.java:78)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at android.view.View.performClick(View.java:5191)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at android.view.View$PerformClick.run(View.java:20916)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at android.os.Handler.handleCallback(Handler.java:739)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at android.os.Handler.dispatchMessage(Handler.java:95)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at android.os.Looper.loop(Looper.java:145)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at android.app.ActivityThread.main(ActivityThread.java:5972)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at java.lang.reflect.Method.invoke(Native Method)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at java.lang.reflect.Method.invoke(Method.java:372)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
08-23 01:47:51.616: E/AndroidRuntime(3422):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by YeoeunJeong** [comment]
af91f13

실수1. 전역변수와 매개변수 이름을 동일하게 써서 헷갈림. 
실수2. showNewsfeed와 searchTagNewsfeed 의 request URL 을 동일하게적음. 

해결해야할문제1. 검색버튼 클릭 후 백버튼 눌러야 Listview에 검색결과 보임. 혹시 키보드에 가려져서인가 싶어서 키보드를 가려보기도했지만 해결책은 아니었다. ( //keyboard hide 로 주석 달은 부분 )

searchBtn.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                String strSearchTag = searchEditText.getText().toString();
                if (!strSearchTag.equals("")) {
                    frameArr = new ArrayList<Frame>();
                    showNewsfeed(v, frameArr, 1, strSearchTag);

```
                // keyboard hide
                // InputMethodManager imm = (InputMethodManager)
                // activity.getSystemService(Context.INPUT_METHOD_SERVICE);
                // imm.hideSoftInputFromWindow(searchEditText.getWindowToken(),
                // 0);
            }
        }
});
```
